#This should under no circumstances be set to true in modpacks
#If set to true, the mod creates a new global folder, that is global for your user on your computer.
#The created folders will be:
# <user_home>/.minecraft_global_packs/required_datapacks
# <user_home>/.minecraft_global_packs/optional_datapacks
# <user_home>/.minecraft_global_packs/required_resourcepacks
# <user_home>/.minecraft_global_packs/optional_resourcepacks
enable_system_global_packs = false

#This config allows you to add or remove folders or single files as Data-/Resourcepacks
#For that simply specify the file path to the folder/file relative to your .minecraft or instance folder
#With the current config you can place a Datapack into '.minecraft/global_packs/required_data' to force enable a datapack.


[resourcepacks]
required = [
	"global_packs/required_resources/",
	"resourcepacks/Beyond Mines Resources 1.0.6.zip",
    "resourcepacks/EclecticTrove-1.20.1-1.3.0.zip",
	"resourcepacks/Simple Grass Flowers v1.9.0.zip",
	"resourcepacks/xali's Enchanted Books v0.13.0.zip",
	"resourcepacks/FreshAnimations_v1.9.2.zip",
	"resourcepacks/xali's Potions v1.0.zip"
]

[datapacks]
required = [
	"global_packs/required_data/",
	"resourcepacks/ore_geodes_for_strato-1.0.4.zip",
	"resourcepacks/SkyVillages-SupplementariesCompat-1.20.1-1.0.3.1.zip",
	"resourcepacks/SkyVillages-WaystonesCompat-1.20.1-1.0.3.zip"
]

optional = [
    "global_packs/optional_data/"
]